module.exports={
  devServer:{ 
    proxy:{
      '/recommend':{
        target:'https://m.wowdsgn.com',
        //ws:true,
        changeOrigin:true
      },
      '/foo':{
        target:'<other_url>'
      }
    }
  }
}